# Makefile to run pipeline for
# Rock Type Prediction from Drill Telemetry Data (QIO3)

# Join hole-identified data sets (collar + PV drill), add rock class labels
# python join_holes.py collar.csv prdrill.csv

# Label telemetry data

# Split data into train and test sets

# EDA and sanity check report (1)

# Feature engineering for non-telemetry data

# Feature engineering for telemetry Data

# Join and prepare inputs for model

# EDA and sanity check report (2)

# Build model
