```{r}
library(ggridges)
library(tidyverse)
library(ggplot2)

D = read.csv("features.csv", header = TRUE)

D <- D %>% 
    mutate(rock_class = factor(rock_class, levels = c("LIM","IF","AMP","QZ") ))
    

    
plots <- list()
for(nm in names(D)) {
    plots[[nm]] <- ggplot(data=D, aes_string(x=nm, y=D$rock_class)) + geom_density_ridges(bandwidth = 0.05) + scale_x_continuous( expand=c(0,0))
}

seq <- c(2, 3, 5:12)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```

```{r}
seq <- c(13:19)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```

```{r}
seq <- c(20:29)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```


```{r}
seq <- c(30:39)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```


```{r}
seq <- c(40:49)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```


```{r}
seq <- c(50:59)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```


```{r}
seq <- c(60:69)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}
```

```{r}
seq <- c(70:72)

for (p in seq) {
  jpeg(paste(names(D)[p], ".jpg", sep="_r_feat"))
  print(plots[[p]])
  dev.off()
}

```
```